---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - argoproj.io/resources-finalizer
  labels:
    app.kubernetes.io/name: external-secrets
spec:
  project: default
  source:
    repoURL: https://github.com/morheus9/crossplane-infra
    targetRevision: HEAD
    path: charts/external-secrets
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-system
  ignoreDifferences:
    # Ignore status fields managed by External Secrets Operator
    # ServerSideApply=true above eliminates the need to ignore ArgoCD annotations
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /status
    - group: external-secrets.io
      kind: SecretStore
      jsonPointers:
        - /status
    - group: external-secrets.io
      kind: ClusterSecretStore
      jsonPointers:
        - /status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
