---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-provider
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: kubernetes-provider
spec:
  project: default
  source:
    repoURL: https://github.com/morheus9/crossplane-infra
    targetRevision: HEAD
    path: charts/kubernetes-provider
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
